### ISSUE TITLE
(linux-specific) Attempting to run the executable immediately crashes it.

### ISSUE THREAD

**Issue by thetheuser** [trumank/mint#184]
I use Fedora Linux 40 with KDE Plasma and Wayland. I also have OpenSSL 1.1.0w installed. Running the program in the terminal results in the output below followed with an immediate crash:

 INFO drg_mod_integration: writing logs to `/home/user/.local/share/drg-mod-integration/drg-mod-integration.log`
interface 'wl_surface' has no event 2
thread 'main' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/glutin-0.30.10/src/api/egl/surface.rs:239:44:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: rust_begin_unwind
             at /rustc/07688726805d5db0a4bca445a6651d09708041ea/library/std/src/panicking.rs:617:5
   1: core::panicking::panic_fmt
             at /rustc/07688726805d5db0a4bca445a6651d09708041ea/library/core/src/panicking.rs:67:14
   2: core::panicking::panic
             at /rustc/07688726805d5db0a4bca445a6651d09708041ea/library/core/src/panicking.rs:117:5
   3: glutin::api::egl::surface::<impl glutin::api::egl::display::Display>::create_window_surface
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/glutin-0.30.10/src/api/egl/surface.rs:239
   4: <glutin::display::Display as glutin::display::GlDisplay>::create_window_surface
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/glutin-0.30.10/src/display.rs:316:33
   5: eframe::native::run::glow_integration::GlutinWindowContext::on_resume
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/eframe-0.22.0/src/native/run.rs:547:17
   6: <eframe::native::run::glow_integration::GlowWinitApp as eframe::native::run::WinitApp>::on_event
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/eframe-0.22.0/src/native/run.rs:666:13
   7: eframe::native::run::run_and_return::{{closure}}
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/eframe-0.22.0/src/native/run.rs:181:28
   8: winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::run_return
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.6/src/platform_impl/linux/wayland/event_loop/mod.rs:242:9
   9: eframe::native::run::with_event_loop
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.6/src/platform_impl/linux/mod.rs:785:56
  10: eframe::native::run::glow_integration::run_glow
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/eframe-0.22.0/src/native/run.rs:1040:13
  11: eframe::run_native
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/eframe-0.22.0/src/lib.rs:220:13
  12: drg_mod_integration::gui::gui
             at /home/runner/work/drg-mod-integration/drg-mod-integration/src/gui/mod.rs:54:5
  13: drg_mod_integration::main
             at /home/runner/work/drg-mod-integration/drg-mod-integration/src/main.rs:133:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: queue 0x5619e335cc50 destroyed while proxies still attached:
  xdg_wm_base@28 still attached
  wl_output@15 still attached
  zwp_text_input_manager_v3@14 still attached
  xdg_activation_v1@13 still attached
  wl_subcompositor@12 still attached
  zwp_relative_pointer_manager_v1@11 still attached
  zwp_pointer_constraints_v1@10 still attached
  wl_seat@9 still attached
  wl_shm@8 still attached
  wp_fractional_scale_manager_v1@7 still attached
  wp_viewporter@6 still attached
  zxdg_decoration_manager_v1@5 still attached
  wl_compositor@4 still attached
  wl_registry@2 still attached

**Comment by c101vp** [comment]
I had a similar issue happen to me on Arch Linux running Plasma 6 and Wayland, however using [this fork](https://github.com/akiirui/mint), it seems to work fine.

**Comment by c101vp** [comment]
Update: Having tested the app on the exact same system, just running on X11 instead of Wayland, I've determined this to potentially be a Wayland-specific issue. I've only tested the latest release, as I didn't really know how I could build this app. However, the fork that I've listed seems to be up to date with this repo, and it works...
![image](https://github.com/trumank/mint/assets/106934806/d2b21159-3e0b-4206-9278-f239eb59db99)
If I knew how to build this app from source, I could test it out and see if the issue is still present, as the latest release was 9 months ago.

**Comment by 5121f** [comment]
Works fine with XWayland: `env -u WAYLAND_DISPLAY drg_mod_integration`.
